#指定服务端口
server:
  port: 3003
#指定微服务名称
spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://10.112.65.89:8002
#  datasource:
#    druid:
#      db-type: mysql
#      driver-class-name: com.mysql.jdbc.Driver
#      url: ${mysql.url}
#      username: ${mysql.user}
#      password: ${mysql.password}
#      initialSize: 10
#      max-active: 20
#      minIdle: 5
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 30000
#      validationQuery: SELECT 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat,wall,slf4j
#      filter:
#        config:
#          enabled: true
#  flyway:
#    url: ${mysql.url}
#    user: ${mysql.user}
#    password: ${mysql.password}
#    enabled: true
##通用mapper配置
#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#  not-empty: false
#  identity: MYSQL
##pagehelper配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#指定服务中心位置
eureka:
  instance:
    hostname: test
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: localhost:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl.defaultZone: http://10.112.65.89:9001/eureka/
    registry-fetch-interval-seconds: 5
#mysql:
#  url: jdbc:mysql://localhost:3306/cloud_wallet?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
#  user: xhyan
#  password: 1234
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
  endpoint:
    health:
      show-details: ALWAYS
debug: false
